import copy
import equinox as eqx
import jax
import jax.numpy as jnp
import subprocess
import wandb

from .dmm_autoencoder_eqx import DeepMechanisticModel, mse
from .wandb_init_log import log_model_stats
from .training_helper_funcs import get_finite_grads
from common import (EarlyStoppingParams, get_scheduler, optimisers,
                    L1EREG, OEREG, L1DREG, ODREG, L1IREG, OIREG, RECON_LOSS, SYMM_LOSS, debug_mode)  # TODO - fix script imports
from flax.training.early_stopping import EarlyStopping
from jaxtyping import Array, Float, PyTree
from pathlib import Path
from typing import Dict


@eqx.filter_value_and_grad
def loss_and_grads_pretrain(
        diff_model: PyTree,
        static_model: PyTree,
        conf: Dict,
        input_data: Float[Array, '...'],
        targets: Float[Array, '...'],
):
    # recombine the two parts of the model
    model = eqx.combine(diff_model, static_model)
    # Get model output (inflated cell-line-specific parameter deviations)
    pred = jax.vmap(model)(input_data)[0]
    # Loss comprises MSE between predicted kinetic parameter deviations and
    #  those obtained from ODE pretraining.
    loss_value = (
            mse(pred.flatten(), targets.flatten())
            + model.l1_encode_reg(scale=conf["l1reg_encode"])
            + model.orth_encode_reg(scale=conf["oreg_encode"])
            + model.l1_inflate_reg(scale=conf["l1reg_inflate"])
            + model.orth_inflate_reg(scale=conf["oreg_inflate"])
    )

    # if two-headed autoencoder, add decoder terms (reconstruction, encoder-decoder symmetry, and regularisation terms
    # with same scales as encoder)
    if model.reconstruct:
        loss_value += (
                model.l1_decode_reg(scale=conf["l1reg_encode"])
                + model.orth_decode_reg(scale=conf["oreg_encode"])
                + model.reconstruction_loss(x=input_data, scale=conf["recon_loss"])
                + model.symmetry_loss(scale=conf["symm_reg"])
        )
    return loss_value


@eqx.filter_jit
def loss_pretrain(
        model: DeepMechanisticModel,
        conf: Dict,
        input_data: Float[Array, '...'],
        targets: Float[Array, '...'],
):
    # Get model output (inflated cell-line-specific parameter deviations)
    pred = jax.vmap(model)(input_data)[0]
    # Loss comprises MSE between predicted kinetic parameter deviations and
    #  those obtained from ODE pretraining.
    loss_value = (
            mse(pred.flatten(), targets.flatten())
            + model.l1_encode_reg(scale=conf["l1reg_encode"])
            + model.orth_encode_reg(scale=conf["oreg_encode"])
            + model.l1_inflate_reg(scale=conf["l1reg_inflate"])
            + model.orth_inflate_reg(scale=conf["oreg_inflate"])
    )

    # if two-headed autoencoder, add decoder terms (reconstruction, encoder-decoder symmetry, and regularisation terms
    # with same scales as encoder)
    if model.reconstruct:
        loss_value += (
                model.l1_decode_reg(scale=conf["l1reg_encode"])
                + model.orth_decode_reg(scale=conf["oreg_encode"])
                + model.reconstruction_loss(x=input_data, scale=conf["recon_loss"])
                + model.symmetry_loss(scale=conf["symm_reg"])
        )
    return loss_value


# Need to split training into train and train_val (model cannot see the validation we will use for
# entire DMM training!)
def pretrain_network(
        model: DeepMechanisticModel,
        filter_spec: PyTree,
        training_data: Float[Array, '...'],
        training_targets: Float[Array, '...'],
        validation_data: Float[Array, '...'],
        validation_targets: Float[Array, '...'],
        # rfile: Path,
        pretrained_model_file: Path,
        conf: Dict,
        n_epoch,
        early_stopping_params: EarlyStoppingParams,
) -> DeepMechanisticModel:
    """
    Trains the provided autoencoder by solving the optimization problem
    generated by :py:func:`create_pypesto_problem`
    """

    # Get schedule and initialise optimiser
    schedule = get_scheduler(conf, n_epoch)
    opt = optimisers[conf["optimiser"]](schedule)
    opt_state = opt.init(eqx.filter(model, eqx.is_array))

    # Check Early-stopping parameters have been set correctly and instantiate early stopper
    if conf["use_early_stopping"]:
        if early_stopping_params.patience is None:
            raise ValueError("Patience value for early stopping is undefined.")
        elif early_stopping_params.min_improvement is None:
            raise ValueError("Minimum absolute improvement for early stopping is undefined.")
        else:
            early_stopper = EarlyStopping(
                min_delta=early_stopping_params.min_improvement,
                patience=early_stopping_params.patience
            )

    # Keep track of best performing model on validation set (actually a part of the DMM training set)
    best_model = copy.deepcopy(model)
    best_loss_val = jnp.inf

    @eqx.filter_jit
    def make_pretrain_step(
            model: DeepMechanisticModel,
            filter_spec: PyTree,
            opt_state: PyTree,
            input_data: Float[Array, '...'],  # TODO @GiacomoFabrini fix input data shape
            targets: Float[Array, '...'],
            conf: Dict,
    ):
        diff_model, static_model = eqx.partition(model, filter_spec)
        loss_value, grads = loss_and_grads_pretrain(
            diff_model,
            static_model,
            conf,
            input_data,
            targets,
        )
        # ensure gradients are finite
        grads = get_finite_grads(grads)
        updates, opt_state = opt.update(grads, opt_state, model)
        # Update model in `next_model`, but keep current one in `model` for current epoch metric logging
        next_model = eqx.apply_updates(model, updates)
        return next_model, model, opt_state, loss_value, grads

    # Training loop
    for epoch in range(n_epoch + 1):
        # Make training step - model is not updated to get current metrics
        next_model, model, opt_state, loss_train, grads = make_pretrain_step(
            model,
            filter_spec,
            opt_state,
            training_data,
            training_targets,
            conf,
        )

        # Evaluate validation loss term
        loss_val = loss_pretrain(
            model=model,
            conf=conf,
            input_data=validation_data,
            targets=validation_targets,
        )

        # Update best model and best loss estimate
        if loss_val < best_loss_val:
            best_loss_val = loss_val
            best_model = copy.deepcopy(model)

        # Log loss_train and loss_val
        wandb.log(
            {
                "loss_train": loss_train,
                "loss_val": loss_val,
            },
            step=epoch
        )

        # Set up regularisation logging
        reg_funs = [
            # Encoder
            model.l1_encode_reg,
            model.orth_encode_reg,
            # Inflater
            model.l1_inflate_reg,
            model.orth_inflate_reg,
        ]
        log_labels = [
            # Encoder
            L1EREG, OEREG,
            # Inflater
            L1IREG, OIREG
        ]
        hp_names = [
            # Encoder
            L1EREG, OEREG,
            # Inflater
            L1IREG, OIREG
        ]

        if model.reconstruct:
            # include decoder regularisation terms
            reg_funs.extend([model.l1_decode_reg, model.orth_decode_reg])
            log_labels.extend([L1DREG, ODREG])
            hp_names.extend([L1EREG, OEREG])  # scales of decoder reg match encoder!
            # log additional loss terms (reconstruction and symmetry loss)
            wandb.log(
                {
                    # for reconstruction loss: log validation loss
                    RECON_LOSS: model.reconstruction_loss(
                        x=validation_data,
                        scale=conf[RECON_LOSS],
                    ),
                    SYMM_LOSS: model.symmetry_loss(scale=conf[SYMM_LOSS])
                },
                step=epoch,
            )
        # Log input-independent regularisation terms (same across training and validation)
        for (
                reg_fun,
                log_label,
                hp_name
        ) in zip(
                reg_funs,
                log_labels,
                hp_names,
        ):
            # this is where the scale parameter of the various regularisation
            # methods get changed via the hyperparameters in training_configuration.py
            if conf[hp_name] > 0:
                # Simply compute the value of the function
                value_reg = reg_fun(scale=conf[hp_name])
                wandb.log({log_label: value_reg}, step=epoch)

        # Overwrite `model` with updated `next_model`
        model = next_model

        # Log param values and grads every 5 epochs + check early-stopping criteria
        if epoch % 5 == 0:
            wandb.log(
                {
                  **log_model_stats(model, grads, pretrain=True)
                },
                step=epoch,
            )

            if conf["use_early_stopping"]:
                # Update early stopper
                early_stopper = early_stopper.update(loss_val)
                # Debugging statements
                if debug_mode:
                    print(
                        f"epoch {epoch} | "
                        f"loss_val {loss_val} | "
                        f"has improved? {early_stopper.has_improved} | "
                        f"patience count {early_stopper.patience_count}"
                    )
                # Log current patience count
                wandb.log(
                    {
                        "patience_counter": early_stopper.patience_count,
                    },
                    step=epoch,
                )
                # Stop training if we have run out of patience
                if early_stopper.should_stop:
                    print(f'Met early stopping criteria, breaking at epoch {epoch}')
                    break
    print(f'best loss_val: {best_loss_val}')
    wandb.log({"final_epoch": epoch})
    # # Save best pretrained model -- not in use for now
    # pretrained_model_file.parent.mkdir(exist_ok=True, parents=True)
    # best_model.save(pretrained_model_file)
    # # Log serialised pretrained model
    # wandb.log_model(path=pretrained_model_file, name="nn_pretrained_model")
    wandb_stripped_dir = wandb.run.dir.rsplit('/files', 1)[0]
    command = f"wandb sync {wandb_stripped_dir}"
    wandb.finish()
    try:
        _ = subprocess.run(command, shell=True)
    except subprocess.CalledProcessError as e:
        raise ValueError(f"Error syncing wandb directory: {e}")
    return best_model
