import equinox as eqx
# import itertools as itt
import jax
import jax.numpy as jnp
# import numpy as np
import pypesto
import wandb

from .dmm_autoencoder_eqx import DeepMechanisticModel, mse
from .wandb_init import log_model_stats
from .deepcomponent_eqx import DeepComponent
from common import EarlyStoppingParams, get_scheduler, optimisers, L1EREG, OEREG, L1IREG, OIREG, RECON_LOSS, SYMM_LOSS
from flax.training.early_stopping import EarlyStopping
from jaxtyping import Array, Float, PyTree
# from pathlib import Path
from typing import Dict


# trace_path = Path(__file__).parents[1] / "traces"
# TRACE_FILE_TEMPLATE = "{pathway}__{data}__{n_hidden}__{job}__{{id}}.csv"


def get_weights(
        module: DeepComponent
) -> jnp.ndarray:
    weights = jnp.concatenate(
        [
            module.layers[i].weight.flatten()
            for i in range(len(module.layers))
        ]
    )
    return weights


@eqx.filter_value_and_grad
def loss_and_grads_pretrain(
        diff_model: PyTree,
        static_model: PyTree,
        conf: Dict,
        input_data: Float[Array, '...'],
        targets: Float[Array, '...'],
):
    # recombine the two parts of the model
    model = eqx.combine(diff_model, static_model)
    # Get model output and remove components corresponding to global kinetic parameters
    pred = model(input_data)[0][len(model.kin_params_combiner.learned_global_kin_params):]
    # Loss comprises MSE between predicted kinetic parameter deviations and
    #  those obtained from ODE pretraining.
    loss_value = (
            mse(pred, targets)
            + model.l1_encode_reg(scale=conf["l1reg_encode"])
            + model.orth_encode_reg(scale=conf["oreg_encode"])
            + model.l1_inflate_reg(scale=conf["l1reg_inflate"])
            + model.orth_inflate_reg(scale=conf["oreg_inflate"])
    )

    # if two-headed autoencoder, add decoder terms (reconstruction + encoder-decoder symmetry)
    if model.reconstruct:
        loss_value += (
                model.reconstruction_loss(x=input_data, scale=conf["recon_loss"])
                + model.symmetry_loss(scale=conf["symm_reg"])
        )
    return loss_value


@eqx.filter_jit
def loss_pretrain(
        model: DeepMechanisticModel,
        conf: Dict,
        input_data: Float[Array, '...'],
        targets: Float[Array, '...'],
):
    # Get model output and remove components corresponding to global kinetic parameters
    pred = model(input_data)[0][len(model.kin_params_combiner.learned_global_kin_params):]
    # Loss comprises MSE between predicted kinetic parameter deviations and
    #  those obtained from ODE pretraining.
    loss_value = (
            mse(pred, targets)
            + model.l1_encode_reg(scale=conf["l1reg_encode"])
            + model.orth_encode_reg(scale=conf["oreg_encode"])
            + model.l1_inflate_reg(scale=conf["l1reg_inflate"])
            + model.orth_inflate_reg(scale=conf["oreg_inflate"])
    )

    # if two-headed autoencoder, add decoder terms (reconstruction + encoder-decoder symmetry)
    if model.reconstruct:
        loss_value += (
                model.reconstruction_loss(x=input_data, scale=conf["recon_loss"])
                + model.symmetry_loss(scale=conf["symm_reg"])
        )
    return loss_value


# Need to split training into train and train_val (model cannot see the validation we will use for
# entire DMM training!)
def pretrain_network(
        model: DeepMechanisticModel,
        filter_spec: PyTree,
        training_data: Float[Array, '...'],
        training_targets: Float[Array, '...'],
        validation_data: Float[Array, '...'],
        validation_targets: Float[Array, '...'],
        # rfile: Path,
        conf: Dict,
        n_epoch,
        early_stopping_params: EarlyStoppingParams,
) -> pypesto.Result:
    """
    Trains the provided autoencoder by solving the optimization problem
    generated by :py:func:`create_pypesto_problem`
    """

    # Get schedule and initialise optimiser
    schedule = get_scheduler(conf, n_epoch)
    opt = optimisers[conf["optimiser"]](schedule)
    opt_state = opt.init(eqx.filter(model, eqx.is_array))

    # Check Early-stopping parameters have been set correctly and instantiate early stopper
    if conf["use_early_stopping"]:
        if early_stopping_params.patience is None:
            raise ValueError("Patience value for early stopping is undefined.")
        elif early_stopping_params.min_improvement is None:
            raise ValueError("Minimum absolute improvement for early stopping is undefined.")
        else:
            early_stopper = EarlyStopping(
                min_delta=early_stopping_params.min_improvement,
                patience=early_stopping_params.patience
            )

    @eqx.filter_jit
    def make_pretrain_step(
            model: DeepMechanisticModel,
            filter_spec: PyTree,
            opt_state: PyTree,
            input_data: Float[Array, '...'],  # TODO @GiacomoFabrini fix input data shape
            targets: Float[Array, '...'],
            conf: Dict,
    ):
        diff_model, static_model = eqx.partition(model, filter_spec)
        loss_value, grads = loss_and_grads_pretrain(
            diff_model,
            static_model,
            conf,
            input_data,
            targets.flatten(),
        )
        # ensure gradients are finite
        grads = jax.tree_map(
            lambda x: jnp.where(jnp.isfinite(x), x, jnp.zeros_like(x)),
            grads,
        )
        updates, opt_state = opt.update(grads, opt_state, model)
        # Update model in `next_model`, but keep current one in `model` for current epoch metric logging
        next_model = eqx.apply_updates(model, updates)
        return next_model, model, opt_state, loss_value, grads

    # Training loop
    for epoch in range(n_epoch + 1):
        # Make training step - model is not updated to get current metrics
        next_model, model, opt_state, loss_train, grads = make_pretrain_step(
            model,
            filter_spec,
            opt_state,
            training_data,
            training_targets,
            conf,
        )

        # Evaluate validation loss term
        loss_val = loss_pretrain(
            model=model,
            conf=conf,
            input_data=validation_data,
            targets=validation_targets.flatten(),
        )

        # Log loss_train and loss_val, as well as param values and grads
        # TODO @GiacomoFabrini add param value and grad logging
        wandb.log(
            {
                "loss_train": loss_train,
                "loss_val": loss_val,
            },
            step=epoch
        )

        # Log individual regularisation terms - not input dependent (same for train and val)
        for reg_fun, label in zip(
                (
                    model.l1_encode_reg,
                    model.orth_encode_reg,
                    model.l1_inflate_reg,
                    model.orth_inflate_reg,
                ),
                (L1EREG, OEREG, L1IREG, OIREG),
        ):
            # this is where the scale parameter of the various regularisation
            # methods get changed via the hyperparameters in training_configuration.py
            if conf[label] > 0:
                # Simply compute the value of the function
                value_reg = reg_fun(scale=conf[label])
                wandb.log({label: value_reg}, step=epoch)
        if model.reconstruct:
            # log additional loss terms in case of two-headed deep autoencoder
            wandb.log(
                {
                    # log validation reconstruction loss (different between training and validation)
                    RECON_LOSS: model.reconstruction_loss(
                        x=validation_data,
                        scale=conf[RECON_LOSS],
                    ),
                    SYMM_LOSS: model.symmetry_loss(scale=conf[SYMM_LOSS])
                },
                step=epoch,
            )

        # Overwrite `model` with updated `next_model`
        model = next_model

        # Log rmse values every 5 epochs + check early-stopping criteria
        if epoch % 5 == 0:
            # TODO @GiacomoFabrini - log param values and grads
            wandb.log(
                {
                  **log_model_stats(model, grads, pretrain=True)
                },
                step=epoch,
            )

            if conf["use_early_stopping"]:
                # Update early stopper
                early_stopper = early_stopper.update(loss_val)
                # Debugging statements
                print(
                    f"epoch {epoch} | "
                    f"loss_val {loss_val} | "
                    f"has improved? {early_stopper.has_improved} | "
                    f"patience count {early_stopper.patience_count}"
                )
                # Log current patience count
                wandb.log(
                    {
                        "patience_counter": early_stopper.patience_count,
                    },
                    step=epoch,
                )
                # Stop training if we have run out of patience
                if early_stopper.should_stop:
                    print(f'Met early stopping criteria, breaking at epoch {epoch}')
                    break

    wandb.log({"final_epoch": epoch})
    wandb.finish()

    # TODO @GiacomoFabrini - need to serialise model in some way?!

    return model
