import equinox as eqx
import git
# import itertools as itt
import jax
import jax.numpy as jnp
# import numpy as np
import pypesto
import wandb

from .dmm_autoencoder_eqx import DeepMechanisticModel, mse
from .deepcomponent_eqx import DeepComponent
from common import Conf, EarlyStoppingParams
from flax.training.early_stopping import EarlyStopping
from jaxtyping import Array, Float, Int, PyTree
from optax import adam, linear_schedule
from pathlib import Path
from typing import Dict


# trace_path = Path(__file__).parents[1] / "traces"
# TRACE_FILE_TEMPLATE = "{pathway}__{data}__{n_hidden}__{job}__{{id}}.csv"


def get_weights(
        module: DeepComponent
) -> jnp.ndarray:
    weights = jnp.concatenate(
        [
            module.layers[i].weight.flatten()
            for i in range(len(module.layers))
        ]
    )
    return weights


@eqx.filter_value_and_grad
def loss_and_grads_pretrain(
        diff_model: PyTree,
        static_model: PyTree,
        conf: Conf,
        input_data: Float[Array, '...'],
        targets: Float[Array, '...'],
):
    # recombine the two parts of the model
    model = eqx.combine(diff_model, static_model)
    # Get model output and remove components corresponding to global kinetic parameters
    pred = model(input_data)[0][len(model.kin_params_combiner.learned_global_kin_params):]
    # Loss comprises MSE between predicted kinetic parameter deviations and
    #  those obtained from ODE pretraining.
    loss_value = (
            mse(pred, targets)
            + model.l1_encode_reg(scale=conf["l1reg_encode"])
            + model.orth_encode_reg(scale=conf["oreg_encode"])
            + model.l1_inflate_reg(scale=conf["l1reg_inflate"])
            + model.orth_inflate_reg(scale=conf["oreg_inflate"])
    )

    # if two-headed autoencoder, add decoder terms (reconstruction + encoder-decoder symmetry)
    if model.reconstruct:
        loss_value += (
                model.reconstruction_loss(x=input_data, scale=conf["recon_loss"])
                + model.symmetry_loss(scale=conf["symm_reg"])
        )
    return loss_value


@eqx.filter_jit
def loss_pretrain(
        model: DeepMechanisticModel,
        conf: Conf,
        input_data: Float[Array, '...'],
        targets: Float[Array, '...'],
):
    # Get model output and remove components corresponding to global kinetic parameters
    pred = model(input_data)[0][len(model.kin_params_combiner.learned_global_kin_params):]
    # Loss comprises MSE between predicted kinetic parameter deviations and
    #  those obtained from ODE pretraining.
    loss_value = (
            mse(pred, targets)
            + model.l1_encode_reg(scale=conf["l1reg_encode"])
            + model.orth_encode_reg(scale=conf["oreg_encode"])
            + model.l1_inflate_reg(scale=conf["l1reg_inflate"])
            + model.orth_inflate_reg(scale=conf["oreg_inflate"])
    )

    # if two-headed autoencoder, add decoder terms (reconstruction + encoder-decoder symmetry)
    if model.reconstruct:
        loss_value += (
                model.reconstruction_loss(x=input_data, scale=conf["recon_loss"])
                + model.symmetry_loss(scale=conf["symm_reg"])
        )
    return loss_value


L1EREG = "l1reg_encode"
OEREG = "oreg_encode"
L1IREG = "l1reg_inflate"
OIREG = "oreg_inflate"
RECON_LOSS = "recon_loss"
SYMM_LOSS = "symm_reg"


# Need to split training into train and train_val (model cannot see the validation we will use for
# entire DMM training!)
def pretrain_network(
        model: DeepMechanisticModel,
        filter_spec: PyTree,
        training_data: Float[Array, '...'],
        training_targets: Float[Array, '...'],
        validation_data: Float[Array, '...'],
        validation_targets: Float[Array, '...'],
        # rfile: Path,
        conf: Conf,
        schedule_config: Dict,
        n_epoch,
        early_stopping_params: EarlyStoppingParams,
) -> pypesto.Result:
    """
    Trains the provided autoencoder by solving the optimization problem
    generated by :py:func:`create_pypesto_problem`
    """

    # TODO @GiacomoFabrini - move wandb init to separate function (possibly common?)
    repo = git.Repo(search_parent_directories=True)

    # TODO (LATER) @GiacomoFabrini - what needs to be done in case of linear benchmark?
    #  Implement checks and additional logic
    if (len(conf["encoder_layer_sizes"]) == 0) and (len(conf["inflater_layer_sizes"]) == 0):
        # default is "relu" but it is not applied unless there is at least 1 hidden layer
        activation_fn_tag = "None"
        linear_benchmark_tag = conf["linear_benchmark"]
    else:
        activation_fn_tag = conf["activation_fn_name"]
        # in these circumstances, linear_benchmark gets ignored
        linear_benchmark_tag = "overridden"

    wandb.init(
        project=f"DeepMechanisticModels.{conf['data']}.{conf['model']}",
        group=f"{conf['context']}_{conf['features']}_network_pretrain",  # to separate from the usual groups
        config={
            **conf,
            "use_early_stopping": conf["use_early_stopping"],  # early-stopping enabled/disabled
            "patience": early_stopping_params.patience
            if conf["use_early_stopping"] else None,
            "min_improvement": early_stopping_params.min_improvement
            if conf["use_early_stopping"] else None,
            "schedule_config": schedule_config,
            "optimizer": "adam",
            "scheduler": "linear",
            "reconstruct": conf["reconstruct"],
        },
        name="__".join(
            str(hyperparam_label)
            for hyperparam_label in (
                conf["samples"],
                conf["n_hidden"],
                conf["orth_reg_strategy"],
                activation_fn_tag,
                conf["reconstruct"],
                linear_benchmark_tag,
                conf["encoder_layer_sizes"],
                conf["encoder_layer_biases"],
                conf["inflater_layer_sizes"],
                conf["inflater_layer_biases"],
                conf["decoder_layer_biases"] if conf["reconstruct"] else None,
                conf["l1reg_encode"],
                conf["oreg_encode"],
                conf["l1reg_inflate"],
                conf["oreg_inflate"],
                conf["recon_loss"] if conf["reconstruct"] else None,
                conf["symm_reg"] if conf["reconstruct"] else None,
                conf["job"],
            )
        ),
        settings=wandb.Settings(
            start_method="fork",
            git_commit=repo.head.object.hexsha,
            git_remote_url=repo.remotes.origin.url,
        ),
        tags=[
            "deep_model",
            "network_pretraining",
            "early_stop" if conf["use_early_stopping"] else "no_early_stop",
        ]
    )

    # Define W&B metrics in modular fashion
    metrics = {
        "loss_train": "min",
        "loss_val": "min",
        "patience_counter": None,
        L1EREG: "min",
        OEREG: "min",
        L1IREG: "min",
        OIREG: "min",
        RECON_LOSS: "min",
        SYMM_LOSS: "min",
    }
    for metric in metrics.keys():
        # if metric summary not specified
        if metrics[metric] is None:
            wandb.define_metric(metric)
        else:
            wandb.define_metric(metric, summary=metrics[metric])

    # TODO @GiacomoFabrini - add param value and grad metric definition

    # Optimiser and related schedule defined here
    # TODO @GiacomoFabrini: change optimiser to optax.adamw (weight decay) and change schedule (later?!)
    schedule = linear_schedule(**schedule_config)
    opt = adam(schedule)
    # TODO @GiacomoFabrini: need to replace with equinox-jax optimisation!
    opt_state = opt.init(eqx.filter(model, eqx.is_array))

    # Check Early-stopping parameters have been set correctly and instantiate early stopper
    if early_stopping_params.use_early_stopping:
        if early_stopping_params.patience is None:
            raise ValueError("Patience value for early stopping is undefined.")
        elif early_stopping_params.min_improvement is None:
            raise ValueError("Minimum absolute improvement for early stopping is undefined.")
        else:
            early_stopper = EarlyStopping(
                min_delta=early_stopping_params.min_improvement,
                patience=early_stopping_params.patience
            )

    @eqx.filter_jit
    def make_pretrain_step(
            model: DeepMechanisticModel,
            filter_spec: PyTree,
            opt_state: PyTree,
            input_data: Float[Array, '...'],  # TODO @GiacomoFabrini fix input data shape
            targets: Float[Array, '...'],
            conf: Conf,
    ):
        diff_model, static_model = eqx.partition(model, filter_spec)
        loss_value, grads = loss_and_grads_pretrain(
            diff_model,
            static_model,
            conf,
            input_data,
            targets.flatten(),
        )
        # ensure gradients are finite
        grads = jax.tree_map(
            lambda x: jnp.where(jnp.isfinite(x), x, jnp.zeros_like(x)),
            grads,
        )
        updates, opt_state = opt.update(grads, opt_state, model)
        model = eqx.apply_updates(model, updates)
        return model, opt_state, loss_value, grads

    # Training loop
    for epoch in range(n_epoch + 1):
        # Make training step - model is updated
        model, opt_state, loss_train, grads = make_pretrain_step(
            model,
            filter_spec,
            opt_state,
            training_data,
            training_targets,
            conf,
        )

        # Evaluate validation loss term
        loss_val = loss_pretrain(
            model=model,
            conf=conf,
            input_data=validation_data,
            targets=validation_targets.flatten(),
        )

        # Log loss_train and loss_val, as well as param values and grads
        # TODO @GiacomoFabrin add param value and grad logging
        wandb.log(
            {
                "loss_train": loss_train,
                "loss_val": loss_val,
            },
            step=epoch
        )

        # Log individual regularisation terms - not input dependent (same for train and val)
        for reg_fun, label in zip(
                (
                        model.l1_encode_reg,
                        model.orth_encode_reg,
                        model.l1_inflate_reg,
                        model.orth_inflate_reg,
                ),
                (L1EREG, OEREG, L1IREG, OIREG),
        ):
            # this is where the scale parameter of the various regularisation
            # methods get changed via the hyperparameters in training_configuration.py
            if conf[label] > 0:
                # Simply compute the value of the function
                value_reg = reg_fun(scale=conf[label])
                wandb.log({label: value_reg}, step=epoch)
        if model.reconstruct:
            # log additional loss terms in case of two-headed deep autoencoder
            wandb.log(
                {
                    # log validation reconstruction loss (different between training and validation)
                    RECON_LOSS: model.reconstruction_loss(
                        x=validation_data,
                        scale=conf[RECON_LOSS],
                    ),
                    SYMM_LOSS: model.symmetry_loss(scale=conf[SYMM_LOSS])
                },
                step=epoch,
            )

        # Log rmse values every 5 epochs + check early-stopping criteria
        if epoch % 5 == 0:
            # TODO @GiacomoFabrini - log param values and grads
            # wandb.log(
            #     {
            #
            #     },
            #     step=epoch,
            # )

            if conf["use_early_stopping"]:
                # Update early stopper
                early_stopper = early_stopper.update(loss_val)
                # Debugging statements
                print(
                    f"epoch {epoch} | "
                    f"loss_val {loss_val} | "
                    f"has improved? {early_stopper.has_improved} | "
                    f"patience count {early_stopper.patience_count}"
                )
                # Log current patience count
                wandb.log(
                    {
                        "patience_counter": early_stopper.patience_count,
                    },
                    step=epoch,
                )
                # Stop training if we have run out of patience
                if early_stopper.should_stop:
                    print(f'Met early stopping criteria, breaking at epoch {epoch}')
                    break

    wandb.log({"final_epoch": epoch})
    wandb.finish()

    # TODO @GiacomoFabrini - need to serialise model in some way?!

    return model
