import logging
from pathlib import Path
from typing import Dict, Tuple

import fides
import numpy as np
import pandas as pd
import pypesto
from pypesto.history import HistoryOptions
from pypesto.objective.jax import JaxObjective
from pypesto.optimize import FidesOptimizer, OptimizeOptions, minimize

from .autoencoder import DeepMechanisticModel
from .problem import Problem

trace_path = Path(__file__).parents[1] / "traces"
TRACE_FILE_TEMPLATE = "{pathway}__{data}__{n_hidden}__{job}__{{id}}.csv"


def generate_pypesto_objective(ae: DeepMechanisticModel) -> JaxObjective:
    """
    Creates a pypesto objective function (this is the loss function) that
    needs to be minimized to train the respective autoencoder

    :param ae:
        Autoencoder that will be trained

    :returns:
        Objective function that needs to be minimized for training.
    """

    return JaxObjective(
        ae.pypesto_subproblem.objective, ae.embedding, x_names=ae.x_names
    )


def create_pypesto_problem(
    ae: DeepMechanisticModel, problem: Problem
) -> pypesto.Problem:
    """
    Creates a pypesto pypesto_probme that defines the optimization pypesto_probme that
    needs to be solved for the training of the provided autoencoder

    :param ae:
        Autoencoder that will be trained

    :returns:
        Optimization pypesto_probme that needs to be solved for training.
    """
    return pypesto.Problem(
        objective=generate_pypesto_objective(ae),
        x_names=ae.x_names,
        lb=[-np.inf for _ in ae.x_names],
        ub=[np.inf for _ in ae.x_names],
    )


def train(
    ae: DeepMechanisticModel,
    pypesto_problem: pypesto.Problem,
    problem: Problem,
    pretraining_file: Path,
    hfile: Path,
    n_starts: int = 1,
    seed: int = 0,
) -> Tuple[pypesto.Result, Dict]:
    """
    Trains the provided autoencoder by solving the optimization problem
    generated by :py:func:`create_pypesto_problem`
    """
    fides_options = {
        fides.Options.FATOL: 0.0,
        fides.Options.FRTOL: 0,
        fides.Options.XTOL: 1e-8,
        fides.Options.MAXTIME: 3600 * 10,
        fides.Options.MAXITER: 1000,
    }
    opt = FidesOptimizer(
        hessian_update=fides.HybridFixed(),
        options=fides_options,
        verbose=logging.INFO,
    )

    np.random.seed(seed)

    optimize_options = OptimizeOptions(
        allow_failed_starts=True,
    )

    if pretraining_file is not None and pretraining_file.exists():
        pretraining = pd.read_csv(pretraining_file, index_col=0)
        xi = pretraining.values[0, :]
    else:
        xi = []
        for xname in pypesto_problem.x_names:
            lb, ub, _ = problem.bounds[xname.split("_")[-1]]
            xi.append(np.random.random() * (ub - lb) + lb)
        xi = np.array(xi)

    # use first couple of PCA components
    w = np.vstack(
        (
            np.eye(ae.n_latent),
            np.zeros((ae.n_features - ae.n_latent, ae.n_latent)),
        )
    ).flatten()

    pypesto_problem.x_guesses_full = np.expand_dims(np.hstack([w, xi]), 1).T

    if hfile is not None:
        Path.unlink(hfile, missing_ok=True)
        history_options = HistoryOptions(
            trace_record=True,
            trace_record_grad=True,
            trace_record_hess=False,
            trace_record_res=False,
            trace_record_sres=False,
            storage_file=str(hfile),
        )
    else:
        history_options = None

    return (
        minimize(
            pypesto_problem,
            opt,
            n_starts=n_starts,
            options=optimize_options,
            filename=None,
            history_options=history_options,
        ),
        fides_options,
    )
