import git
import itertools as itt
import numpy as np
import petab
import pypesto
import wandb

from .dmm_autoencoder_eqx import DeepMechanisticModel
from amici.petab_objective import rdatas_to_simulation_df
from common import Conf, EarlyStoppingParams
from flax.training.early_stopping import EarlyStopping
# doc: flax.readthedocs.io/en/latest/_modules/flax/training/early_stopping.html
from jax import value_and_grad
from jaxtyping import Array
from optax import adam, apply_updates, linear_schedule
from pathlib import Path
from .problem import Problem
from pypesto import Result
from pypesto.C import MODE_RES, RDATAS
from pypesto.objective.jax import JaxObjective
from pypesto.result.optimize import OptimizeResult, OptimizerResult
from pypesto.store import OptimizationResultHDF5Writer
from typing import Dict


trace_path = Path(__file__).parents[1] / "traces"
TRACE_FILE_TEMPLATE = "{pathway}__{data}__{n_hidden}__{job}__{{id}}.csv"


def generate_pypesto_objective(ae: DeepMechanisticModel) -> JaxObjective:
    """
    Creates a pypesto objective function (this is the loss function) that
    needs to be minimized to train the respective autoencoder

    :returns:
        Objective function that needs to be minimized for training.
    """

    return JaxObjective(
        objective=ae.pypesto_subproblem.objective,
        # ae.embedding,  # going away in next pypesto release
        x_names=ae.x_names
    )


def create_pypesto_problem(
    ae: DeepMechanisticModel,
) -> pypesto.Problem:
    """
    Creates a pypesto.Problem that defines the optimization problem to solve
    for the training of the provided DeepMechanisticModel/Autoencoder (ae).

    :param ae:
        Autoencoder that will be trained

    :returns:
        Optimization pypesto_problem that needs to be solved for training.
    """

    # TODO @GiacomoFabrini remove all arguments apart from the objective -- what about x_names?
    return pypesto.Problem(
        objective=generate_pypesto_objective(ae),
        x_names=ae.x_names,
        lb=[-np.inf for _ in ae.x_names],
        ub=[np.inf for _ in ae.x_names],
    )


L1EREG = "l1reg_encode"
OEREG = "oreg_encode"
L1IREG = "l1reg_inflate"
OIREG = "oreg_inflate"
RECON_LOSS = "recon_loss"
SYMM_LOSS = "symm_reg"


def train(
        input_features_train,
        model: DeepMechanisticModel,
        problem_train: pypesto.Problem,
        problem_test: pypesto.Problem,
        rfile: Path,
        conf: Conf,
        schedule_config: Dict,
        n_epoch,
        x0,  # PEtab-compatible mapping from deep_inflater/kin_params_combiner output
        early_stopping_params: EarlyStoppingParams,
) -> pypesto.Result:

    """
    Trains the provided autoencoder by solving the optimization problem
    generated by :py:func:`create_pypesto_problem`
    """

    repo = git.Repo(search_parent_directories=True)

    wandb.init(
        project=f"DeepMechanisticModels.{conf['data']}.{conf['model']}",
        group=f"{conf['context']}_{conf['features']}",
        config={
            **conf,
            "patience": early_stopping_params.patience
                if early_stopping_params.use_early_stopping else None,
            "min_improvement": early_stopping_params.min_improvement
                if early_stopping_params.use_early_stopping else None,
            "schedule_config": schedule_config,
            "optimizer": "adam",
            "scheduler": "linear",
            "reconstruct": conf.reconstruct,
        },
        name="__".join(
            hyperparam_label+":"+str(conf.hyperparam_label)  # e.g. samples:0_5__n_hidden:2__orth_reg_strategy:L2__ etc.
            for hyperparam_label in (
                conf["samples"],
                conf["n_hidden"],
                conf["orth_reg_strategy"],
                conf["activation_fn_name"],
                conf["reconstruct"],
                conf["encoder_layer_sizes"],
                conf["encoder_layer_biases"],
                conf["inflater_layer_sizes"],
                conf["inflater_layer_biases"],
                conf["decoder_layer_biases"] if conf.reconstruct else None,
                conf["l1reg_encode"],
                conf["oreg_encode"],
                conf["l1reg_inflate"],
                conf["oreg_inflate"],
                conf["scale_recon_loss"] if conf.reconstruct else None,
                conf["scale_symm_loss"] if conf.reconstruct else None,
                conf["job"],
            )
        ),
        settings=wandb.Settings(
            start_method="fork",
            git_commit=repo.head.object.hexsha,
            git_remote_url=repo.remotes.origin.url,
        ),
    )

    # Define W&B metrics in modular fashion
    metrics = {
        "rmse_train": "min",
        "rmse_val": "min",
        "patience_counter": None,
        "fval": "min",
        "loss": "min",
        L1EREG: "min",
        OEREG: "min",
        L1IREG: "min",
        OIREG: "min",
        RECON_LOSS: "min",
        SYMM_LOSS: "min",
    }
    for metric in metrics.keys():
        # if metric summary not specified
        if metrics[metric] is None:
            wandb.define_metric(metric)
        else:
            wandb.define_metric(metric, summary=metrics[metric])

    # TODO @GiacomoFabrini - this needs to be changed!
    par_labels = ("encode", "inflate", "kinetic")
    par_dims = (
        model.n_encode_weights,
        model.n_encoder_pars,
        model.n_kin_params,
    )
    for val_type, xname in itt.product(("x", "g"), par_labels):
        wandb.define_metric(f"{val_type}_{xname}")

    # This will be a PEtab-compatible format
    x = x0.copy()

    # Optimiser and related schedule defined here
    # TODO @GiacomoFabrini: change optimiser to optax.adamw (weight decay) and change schedule (later?!)
    schedule = linear_schedule(**schedule_config)
    opt = adam(schedule)
    # TODO @GiacomoFabrini: need to replace with equinox-jax optimisation!
    opt_state = opt.init(x)

    opt_x = x.copy()
    opt_fval = np.inf
    opt_grads = np.NaN * np.ones_like(x)
    rmse_test_min = np.inf

    # Check Early-stopping parameters have been set correctly and instantiate early stopper
    if early_stopping_params.use_early_stopping:
        if early_stopping_params.patience is None:
            raise ValueError("Patience value for early stopping is undefined.")
        elif early_stopping_params.min_improvement is None:
            raise ValueError("Minimum absolute improvement for early stopping is undefined.")
        else:
            early_stopper = EarlyStopping(
                min_delta=early_stopping_params.min_improvement,
                patience=early_stopping_params.patience
            )

    # Training loop
    for epoch in range(n_epoch + 1):
        loss, fval = model.loss_fn(
            input_data=input_features_train,
            problem_train=problem_train,
            scale_l1reg_encode=conf.scale_l1reg_encode,
            scale_oreg_encode=conf.scale_oreg_encode,
            scale_l1reg_inflate=conf.scale_l1reg_inflate,
            scale_oreg_inflate=conf.scale_oreg_inflate,
            scale_recon_loss=conf.scale_recon_loss,
            scale_symm_loss=conf.scale_symm_loss,
        )

        # TODO @GiacomoFabrini only compute function values and log (restore) -- OK
        for reg_fun, label in zip(
            (
                model.l1_encode_reg,
                model.orth_encode_reg,
                model.l1_inflate_reg,
                model.orth_inflate_reg,
                model.symmetry_loss,
            ),
            (L1EREG, OEREG, L1IREG, OIREG, SYMM_LOSS),
        ):
            # this is where the scale parameter of the various regularisation
            # methods get changed via the hyperparameters in training_configuration.py
            if conf[label] > 0:
                # Simply compute the value of the function
                value_reg = reg_fun(scale=conf[label])
                wandb.log({label: value_reg}, step=epoch)
        # Log Reconstruction Loss (which requires additional input: input_features_train)
        wandb.log(
            {
                RECON_LOSS: model.reconstruction_loss(
                    x=input_features_train,
                    scale=conf.RECON_LOSS
                )
            }
        )
        # Log fval and loss function value at this epoch
        wandb.log(
            {
                "fval": fval,
                "loss": loss
            },
            step=epoch
        )

        # TODO @GiacomoFabrini here is where you need to perform the optimisation step!
        ###
        ###
        ###

        if epoch % 5 == 0:
            rmse_dict = dict()
            # evaluate rmse on train and test dataset only after a certain number (5) of epochs
            for dataset, pp in zip(
                ("train", "test"), (problem_train, problem_test)
            ):
                rmse_dict[dataset] = rmse(pp, x)

            if rmse_dict["test"] < rmse_test_min:
                rmse_test_min = rmse_dict["test"]
                # TODO @GiacomoFabrini this needs to be changed as well
                opt_x = x.copy()
                opt_fval = fval
                opt_grads = grads.copy()

            wandb.log(
                {
                    "rmse_train": rmse_dict["train"],
                    "rmse_val": rmse_dict["test"],
                    **{
                        f"{val_type}_{xname}": None
                        if not np.all(np.isfinite(value))
                        else wandb.Histogram(value)
                        if val_type == "x"
                        else wandb.Histogram(
                            np.log10(np.abs(value[value != 0]))
                        )
                        # TODO @GiacomoFabrini: need to fix this with proper grads and x - what shall I do with xname?
                        for val_type, values in (
                            ("x", x),
                            ("g", grads),
                        )
                        for xname, value in zip(
                            par_labels,
                            np.split(values, par_dims[:-1]),
                        )
                    },
                },
                step=epoch,
            )

            if early_stopping_params.use_early_stopping:
                # Update early stopper
                early_stopper = early_stopper.update(rmse_dict["test"])
                # Debugging statements
                print(
                    f"epoch {epoch} | "
                    f"loss {rmse_dict['test']} | "
                    f"has improved? {early_stopper.has_improved} | "
                    f"patience count {early_stopper.patience_count}"
                )
                # Log current patience count
                wandb.log(
                    {
                        "patience_counter": early_stopper.patience_count,
                    },
                    step=epoch,
                )
                # Stop training if we have run out of patience
                if early_stopper.should_stop:
                    print(f'Met early stopping criteria, breaking at epoch {epoch}')
                    break

        # TODO @GiacomoFabrini need to change this
        updates, opt_state = opt.update(grads, opt_state)
        x = apply_updates(x, updates)
        # TODO @GiacomoFabrini need to update x here given the updates to the network
        # PSEUDO CODE: x = compute_updated_kinetic_parameters(input_features_train, updates)
        # could be as simple as x = model(input_features_train)[0], i.e. augmented_inflated
        # after the model parameters have been updated!
        x = model(input_features_train)[0]  # i.e. augmented_inflated

        if np.any(np.isnan(x)):
            break

    wandb.log({"final_epoch": epoch})
    wandb.finish()

    # Saving epoch number inside n_fval (number of function evaluations)
    optimization_result = OptimizeResult()
    optimization_result.append(
        OptimizerResult(
            fval=opt_fval,
            n_fval=epoch,  # save epoch number to diagnose early stopping
            x=opt_x,
            grad=opt_grads,
            x0=x0,
            id=str(conf["job"]),
        )
    )
    result = Result(
        problem=problem_train,
        optimize_result=optimization_result,
    )

    rfile.parent.mkdir(exist_ok=True, parents=True)
    writer = OptimizationResultHDF5Writer(str(rfile))
    writer.write(result, overwrite=True)

    return result


def rmse(pp, xx):
    try:
        x = pp.objective.jax_fun(xx)
        obj = pp.objective.base_objective
        amici_model = obj.amici_model
        petab_problem = obj.amici_object_builder.petab_problem
        res = obj(x, mode=MODE_RES, return_dict=True)
        simulation_df = rdatas_to_simulation_df(
            res[RDATAS],
            model=amici_model,
            measurement_df=petab_problem.measurement_df,
        )
        return np.sqrt(
            np.mean(
                np.square(
                    simulation_df[petab.SIMULATION]
                    - petab_problem.measurement_df[petab.MEASUREMENT]
                )
            )
        )
    except Exception as e:
        print(e)
        return np.NaN
