import copy
import equinox as eqx
import numpy as np
import optax
import petab
import pypesto
import subprocess
import wandb

# CHECK WHETHER WE NEED TO ROLL BACK to amici.petab_objective
from amici.petab.simulations import rdatas_to_simulation_df
# from amici.petab_objective import rdatas_to_simulation_df
from common import (Conf, EarlyStoppingParams, get_scheduler, optimisers,
                    RECON_LOSS, SYMM_LOSS, L1EREG, OEREG, L1DREG, ODREG, L1IREG, OIREG, debug_mode,
                    TRAINED_MODEL_WEIGHT_PLOTS)
from .dmm_autoencoder_eqx import DeepMechanisticModel
from .training_helper_funcs import test_save_reload_model
from .wandb_init_log import log_model_stats
from .training_helper_funcs import (apply_filter_to_updates, get_finite_grads,
                                   map_params_to_array, model_output_to_petab_input, plot_model_weights)
from flax.training.early_stopping import EarlyStopping
# doc: flax.readthedocs.io/en/latest/_modules/flax/training/early_stopping.html
from jaxtyping import Array, Float, PyTree
from pathlib import Path
from pypesto import Result
from pypesto.C import MODE_RES, RDATAS
from pypesto.result.optimize import OptimizeResult, OptimizerResult
from pypesto.store import OptimizationResultHDF5Writer
from typing import Dict

trace_path = Path(__file__).parents[1] / "traces"
TRACE_FILE_TEMPLATE = "{pathway}__{data}__{n_hidden}__{job}__{{id}}.csv"


@eqx.filter_value_and_grad
def loss_fn(
        model: DeepMechanisticModel,
        conf: Dict,
        input_data,
        problem_train: pypesto.Problem,
):
    # problem_train.objective() now needs to get in input what was previously the output of the jax_fun, i.e. the output
    # of ae.embedding(x). x contained the parameters (encoder, inflater, kinetic parameters) and ae.embedding(x)
    # transformed the parameters into kinetic parameters (global) + inflated parameters (i.e. input data passed
    # through encoder + inflater and flattened). This is now the first component of the output of the model.
    # call.
    fval = problem_train.objective(
        model_output_to_petab_input(model, input_data)
    )

    loss_value = fval
    if not conf["drop_reg_after_pretrain"]:
        loss_value += (
                model.l1_encode_reg(scale=conf["l1reg_encode"])
                + model.orth_encode_reg(scale=conf["oreg_encode"])
                + model.l1_inflate_reg(scale=conf["l1reg_inflate"])
                + model.orth_inflate_reg(scale=conf["oreg_inflate"])
        )
        if model.reconstruct:
            loss_value += (
                model.l1_decode_reg(scale=conf["l1reg_encode"])
                + model.orth_decode_reg(scale=conf["oreg_encode"])
            )

    if model.reconstruct:
        loss_value += (
                model.reconstruction_loss(x=input_data, scale=conf["recon_loss"])
                + model.symmetry_loss(scale=conf["symm_reg"])
        )

    return loss_value


@eqx.filter_jit
def make_step(
        model: DeepMechanisticModel,
        filter_spec_per_param: PyTree,
        opt: optax.GradientTransformation,
        opt_state: PyTree,
        input_data: Float[Array, '...'],  # TODO @GiacomoFabrini fix input data shape?
        problem_train: pypesto.Problem,
        conf: Dict,
):
    loss_value, grads = loss_fn(
        model,
        conf,
        input_data,
        problem_train,
    )
    grads = get_finite_grads(grads)
    updates, opt_state = opt.update(grads, opt_state, model)
    # Zero-out the updates based on filter_spec_per_param (keep where True).
    # This is equivalent to freezing on a per-parameter basis
    filtered_updates = apply_filter_to_updates(updates, filter_spec_per_param)
    # Update model in `next_model`, but keep current one in `model` for current epoch metric logging
    next_model = eqx.apply_updates(model, filtered_updates)
    return next_model, model, opt_state, loss_value, grads


def train(
        model: DeepMechanisticModel,
        filter_spec_per_param: PyTree,
        problem_train: pypesto.Problem,
        problem_test: pypesto.Problem,
        input_features_train,
        input_features_test,
        rfile: Path,
        model_file: Path,
        samples_name_list_dict: dict,
        conf: Dict,
        n_epoch,
        x0,  # PEtab-compatible embedding of initial parameters
        early_stopping_params: EarlyStoppingParams,
) -> pypesto.Result:
    """
    Trains the provided autoencoder by solving the optimization problem
    generated by :py:func:`create_pypesto_problem`
    """

    # Get schedule and initialise optimiser
    schedule = get_scheduler(conf, n_epoch)
    opt = optimisers[conf["optimiser"]](schedule)
    opt_state = opt.init(eqx.filter(model, eqx.is_array))

    # Initialise default values for early_stopper and epoch
    early_stopper = None
    epoch = 0

    # TODO @GiacomoFabrini Do we still need these? Or can we change them in some way?
    x = x0.copy()
    opt_x = x.copy()
    opt_fval = np.inf
    opt_grads = np.NaN * np.ones_like(x)
    best_model = copy.deepcopy(model)
    rmse_test_min = np.inf

    # Check Early-stopping parameters have been set correctly and instantiate early stopper
    if conf["use_early_stopping"]:
        if early_stopping_params.patience is None:
            raise ValueError("Patience value for early stopping is undefined.")
        elif early_stopping_params.min_improvement is None:
            raise ValueError("Minimum absolute improvement for early stopping is undefined.")
        else:
            early_stopper = EarlyStopping(
                min_delta=early_stopping_params.min_improvement,
                patience=early_stopping_params.patience
            )

    # Training loop
    for epoch in range(n_epoch + 1):
        next_model, model, opt_state, loss_train, grads = make_step(
            model=model,
            filter_spec_per_param=filter_spec_per_param,
            opt=opt,
            opt_state=opt_state,
            input_data=input_features_train,
            problem_train=problem_train,
            conf=conf,
        )

        # Get current fval for logging purposes
        fval = problem_train.objective(
            model_output_to_petab_input(model, input_features_train)
        )

        # Log fval and loss_train at this epoch
        wandb.log(
            {
                "fval": fval,
                "loss": loss_train,
            },
            step=epoch
        )

        # Set up regularisation logging
        reg_funs = [
            # Encoder
            model.l1_encode_reg,
            model.orth_encode_reg,
            # Inflater
            model.l1_inflate_reg,
            model.orth_inflate_reg,
        ]
        log_labels = [
            # Encoder
            L1EREG, OEREG,
            # Inflater
            L1IREG, OIREG
        ]
        hp_names = [
            # Encoder
            L1EREG, OEREG,
            # Inflater
            L1IREG, OIREG
        ]

        if model.reconstruct:
            # include decoder regularisation terms
            reg_funs.extend([model.l1_decode_reg, model.orth_decode_reg])
            log_labels.extend([L1DREG, ODREG])
            hp_names.extend([L1EREG, OEREG])  # scales of decoder reg match encoder!
            # log additional loss terms (reconstruction - training - and symmetry loss)
            wandb.log(
                {
                    RECON_LOSS: model.reconstruction_loss(
                        x=input_features_train,
                        scale=conf[RECON_LOSS]
                    ),
                    SYMM_LOSS: model.symmetry_loss(scale=conf[SYMM_LOSS])
                },
                step=epoch
            )
        if not conf["drop_reg_after_pretrain"]:
            # Log input-independent regularisation terms (same across training and validation)
            for (
                    reg_fun,
                    log_label,
                    hp_name
            ) in zip(
                    reg_funs,
                    log_labels,
                    hp_names,
            ):
                if conf[hp_name] > 0:
                    # Simply compute the value of the function
                    value_reg = reg_fun(scale=conf[hp_name])
                    wandb.log({log_label: value_reg}, step=epoch)

        # Overwrite model with updated next_model
        model = next_model

        # Update x - same param array that we had before
        x = map_params_to_array(model)
        # Map grads to same shape param array
        grads_array = map_params_to_array(grads)

        # Log rmse values every 5 epochs + check early-stopping criteria
        if epoch % 5 == 0:
            rmse_dict = dict()
            # evaluate rmse on train and test dataset only after a certain number (5) of epochs
            for dataset, pp, input_data in zip(
                    ("train", "test"),
                    (problem_train, problem_test),
                    (input_features_train, input_features_test)
            ):
                rmse_dict[dataset] = rmse(pp, model, input_data)

            if rmse_dict["test"] < rmse_test_min:
                rmse_test_min = rmse_dict["test"]
                best_model = copy.deepcopy(model)
                # TESTS TO ENSURE SAVING AND RELOADING WORKS FOR model_train and model_test
                # test_save_reload_model(
                #     best_model,
                #     model_file,
                #     samples_name_list_dict,
                #     Conf(**conf),
                #     "train",
                #     input_features_train,
                # )
                # test_save_reload_model(
                #     best_model,
                #     model_file,
                #     samples_name_list_dict,
                #     Conf(**conf),
                #     "test",
                #     input_features_test,
                # )
                opt_x = x.copy()
                opt_fval = fval
                opt_grads = grads_array.copy()

            wandb.log(
                {
                    "rmse_train": rmse_dict["train"],
                    "rmse_val": rmse_dict["test"],
                    **log_model_stats(model, grads, pretrain=False)
                },
                step=epoch
            )

            if conf["use_early_stopping"]:
                # Update early stopper
                early_stopper = early_stopper.update(rmse_dict["test"])
                # Debugging statements
                if debug_mode:
                    print(
                        f"epoch {epoch} | "
                        f"rmse_val {rmse_dict['test']} | "
                        f"has improved? {early_stopper.has_improved} | "
                        f"patience count {early_stopper.patience_count}"
                    )
                # Log current patience count
                wandb.log(
                    {
                        "patience_counter": early_stopper.patience_count,
                    },
                    step=epoch
                )
                # Stop training if we have run out of patience
                if early_stopper.should_stop:
                    print(f'Met early stopping criteria, breaking at epoch {epoch}')
                    break

        if np.any(np.isnan(x)):
            # keep track of integration errors
            wandb.log(
                {
                    "integration_error": epoch,
                }
            )
            break

    print(f"Best rmse_val: {rmse_test_min}")
    wandb.log({"final_epoch": epoch})
    wandb_stripped_dir = wandb.run.dir.rsplit('/files', 1)[0]
    command = f"wandb sync {wandb_stripped_dir}"
    plot_model_weights(model, filename=TRAINED_MODEL_WEIGHT_PLOTS.format(**conf))
    wandb.log({"trained_model_weights": wandb.Image(TRAINED_MODEL_WEIGHT_PLOTS.format(**conf))})
    # Save best model
    model_file.parent.mkdir(exist_ok=True, parents=True)
    best_model.save(
        model_file,
        samples_name_list_dict,
    )
    # Log serialised pretrained model
    wandb.log_model(path=model_file, name="trained_dmm")
    wandb.finish()
    try:
        _ = subprocess.run(command, shell=True)
    except subprocess.CalledProcessError as e:
        raise ValueError(f"Error syncing wandb directory: {e}")

    # Saving epoch number inside n_fval (number of function evaluations)
    optimization_result = OptimizeResult()
    optimization_result.append(
        OptimizerResult(
            fval=opt_fval,
            # n_fval=epoch,  # save epoch number to diagnose early stopping
            x=opt_x,
            grad=opt_grads,
            x0=x0,
            id=str(conf["job"]),
        )
    )
    result = Result(
        problem=problem_train,
        optimize_result=optimization_result,
    )

    # Save results
    rfile.parent.mkdir(exist_ok=True, parents=True)
    writer = OptimizationResultHDF5Writer(str(rfile))
    writer.write(result, overwrite=True)
    return result


def rmse(pp,
         model: DeepMechanisticModel,
         input_data):
    try:
        x = model_output_to_petab_input(model, input_data)
        obj = pp.objective.base_objective
        amici_model = obj.amici_model
        petab_problem = obj.amici_object_builder.petab_problem
        res = obj(x, mode=MODE_RES, return_dict=True)
        simulation_df = rdatas_to_simulation_df(
            res[RDATAS],
            model=amici_model,
            measurement_df=petab_problem.measurement_df,
        )
        return np.sqrt(
            np.mean(
                np.square(
                    simulation_df[petab.SIMULATION]
                    - petab_problem.measurement_df[petab.MEASUREMENT]
                )
            )
        )
    except Exception as e:
        print(e)
        return np.NaN
